language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - python setup.py install
  - pip install requests
  - pip install GitPython
  - pip install PyYaml
script:
  - python tests/metamorph_tests.py -v