language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pwd
  - ls
  - python setup.py install
  - pip install -r requirements.txt
script:
  - python tests/metamorph_tests.py -v
